services:
  mongodb:
    image: mongo
    container_name: mongodb-experimental
    ports:
      - "27017:27017"
    volumes:
      - mongo-data-experimental:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: experimental_username
      MONGO_INITDB_ROOT_PASSWORD: experimental_password
      MONGO_INITDB_DATABASE: experimental_database
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs-experimental
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - mongodb
volumes:
  mongo-data-experimental:
